name: Build
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

env:
  PYTHON_VERSION: 3.12

jobs:
  build:
    name: Build
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          push: true
          file: Dockerfile
          tags: latest
          labels: latest
          build-args: |
            GIT_REV=${{ github.sha }}
